### ISSUE TITLE
Startbuchcheck, Anzeige letzte Turniere Akronummer fehlt

### ISSUE THREAD

**Issue by lambda4-ab** [drbv/admidio#2]
wenn man den startbuchcheck aufruft und ein vergangenes turnier auswählt, dann fehlen in der Anzeige die Numern der Akrobatiken

**Comment by powerwuffi** [comment]
Das ist extern und hat nichts direkt mit Admidio zu tun. Es wird nur die Admidio-Datenbank abgefragt.
Die Datenbank wird auch nur für die aktuell gemeldeten Akros abgefragt. 
Für die vergangenen Turniere werden die Startlisten abgefragt und da sind die Nummern nicht enthalten.

Bitte Ticket schließen!

**Comment by lambda4-ab** [comment]
OK sorry ... zeigt aber, das wir an den Schnittstellen zwischen den einzelnen Komponenten auch noch optimieren können.
